Fix pdf generation on windows
PDF generation fails when executed on windows due to the following error
encountered by `asciidoctor`.
```
org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
```

This is most likely a bug originating from either `asciidoctor`, `jruby`
or the combination of both.

Additionally, tests of `cukedoctor-converter` and `cucumber-spi-example`
modules have occurrences of unexpected line endings or paths separators when
executed on windows.

Closes #119